services:
  web:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:test1234@db/app_development
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
    depends_on:
      - redis
  redis:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test1234
  selenium: 
    image: seleniarm/standalone-chromium
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"